name: wpi_app
publish_to: 'none'
description: WPI 심리 검사 애플리케이션
version: 0.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # 로컬 알림
  flutter_local_notifications: ^17.2.4
  
  # 시간대 처리
  timezone: ^0.9.4
  
  # 로컬 저장소 (알림 설정 저장)
  shared_preferences: ^2.2.2
  dio: ^5.4.3+1
  flutter_markdown: ^0.7.1
  
  # 이미지 캡처 및 저장
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/wpi_atom/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Variable.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Variable.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Variable.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Variable.ttf
          weight: 700
    - family: NotoSerifKR
      fonts:
        - asset: assets/fonts/NotoSerifKR-Variable.ttf
          weight: 400
        - asset: assets/fonts/NotoSerifKR-Variable.ttf
          weight: 600
        - asset: assets/fonts/NotoSerifKR-Variable.ttf
          weight: 700
