name: wpi_app
publish_to: 'none'
description: WPI 심리 검사 애플리케이션
version: 0.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # 로컬 알림
  flutter_local_notifications: ^17.2.4
  
  # 시간대 처리
  timezone: ^0.9.4
  
  # 로컬 저장소 (알림 설정 저장)
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  dio: ^5.4.3+1
  flutter_markdown: ^0.7.1
  
  # SVG 아이콘 렌더링
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1

  # 결제 WebView
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.2

  # 소셜 로그인 (계정 연동용)
  kakao_flutter_sdk_user: ^1.10.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FEFDF5"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/wpi_atom/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
          weight: 400
        - asset: assets/fonts/PretendardVariable.ttf
          weight: 500
        - asset: assets/fonts/PretendardVariable.ttf
          weight: 600
        - asset: assets/fonts/PretendardVariable.ttf
          weight: 700
        - asset: assets/fonts/PretendardVariable.ttf
          weight: 800
